apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab-runner-operator
  namespace: openshift-operators
  labels:
    operators.coreos.com/gitlab-runner-operator.openshift-operators: ''
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitlab-runner-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: gitlab-runner-operator.v1.3.0